// _shared/cors.ts — CORS for browser-invoked (callable) Edge Functions.
//
// The Supabase platform does NOT add CORS headers to responses generated by
// the function itself, and it forwards OPTIONS preflight requests to the
// function handler (verified live against the deployed project: OPTIONS
// /functions/v1/* reaches the Deno worker — x-deno-execution-id present —
// and the handler's 405 carried no Access-Control-Allow-* header).
// Browser-invoked functions must therefore answer preflight themselves and
// attach CORS headers to every response.
//
// Security model: JWT auth (verify_jwt) + role/gym checks remain the real
// gate — CORS only decides which browser origins may read responses. We echo
// an explicit allow-list (never a wildcard) so only the intended app origins
// are accepted; every other origin gets no CORS headers and the browser
// blocks the request (fail-closed).

/** Origins allowed to call browser-invoked functions (no wildcard). */
export const ALLOWED_ORIGINS = [
  // Production (Vercel)
  'https://ironpulse-liart.vercel.app',
  // Development (vite dev server — port 3000, see vite.config.js)
  'http://localhost:3000',
  'http://127.0.0.1:3000',
]

/** Methods this function answers (preflight allow-list). */
const CORS_ALLOW_METHODS = 'POST, OPTIONS'

/** Headers the Supabase client libraries send (authorization, apikey,
 * x-client-info, content-type, x-retry-count). */
const CORS_ALLOW_HEADERS =
  'authorization, apikey, x-client-info, content-type, x-retry-count'

/** Preflight cache lifetime in seconds. */
const CORS_MAX_AGE = '3600'

export function isAllowedOrigin(origin: string | null): boolean {
  return !!origin && ALLOWED_ORIGINS.includes(origin)
}

/**
 * CORS response headers for an allowed origin; null when the origin is not
 * allowed (fail-closed — the caller never sees a response it may read).
 */
export function corsHeadersFor(origin: string | null): Record<string, string> | null {
  if (!isAllowedOrigin(origin)) return null
  return {
    'Access-Control-Allow-Origin': origin as string,
    'Access-Control-Allow-Methods': CORS_ALLOW_METHODS,
    'Access-Control-Allow-Headers': CORS_ALLOW_HEADERS,
    'Access-Control-Max-Age': CORS_MAX_AGE,
    Vary: 'Origin',
  }
}

/**
 * Wraps a Deno.serve handler with CORS support: answers OPTIONS preflight
 * directly (204 with CORS headers for allowed origins, plain 204 otherwise)
 * and attaches the CORS headers to every response for allowed origins.
 */
export function withCors(handler: (req: Request) => Promise<Response> | Response) {
  return async (req: Request): Promise<Response> => {
    const origin = req.headers.get('Origin')
    const cors = corsHeadersFor(origin)

    if (req.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: cors || undefined })
    }

    const res = await handler(req)
    if (cors) {
      for (const [key, value] of Object.entries(cors)) res.headers.set(key, value)
    }
    return res
  }
}