/**
 * IRONPULSE — Firebase Storage inventory (Step 8F, READ-ONLY).
 *
 * Lists every object in the Firebase Storage default bucket so the team can
 * plan the Supabase migration (object count, paths, sizes, content types,
 * orphan references).
 *
 * The script NEVER deletes, moves, or rewrites anything.
 *
 * Usage:
 *   1. Provide a service-account JSON via one of:
 *        - env  GOOGLE_APPLICATION_CREDENTIALS=<path to sa.json>
 *        - env  GCP_SA_PATH=<path to sa.json>
 *        - argv: node storage_inventory.js <path to sa.json>
 *   2. Optional: --bucket=<name> to override the default bucket
 *      (default: VITE_FIREBASE_STORAGE_BUCKET from IRONPULSE/.env.production, else 'ironpulse.appspot.com')
 *   3. node scripts/migration/storage_inventory.js
 *
 * Output:
 *   - console table + docs/FIREBASE_STORAGE_INVENTORY.md (regenerated)
 *
 * Requires: @google-cloud/storage (dev dependency). Install if missing:
 *   npm i -D @google-cloud/storage
 */
const fs = require('fs')
const path = require('path')

async function main() {
  const args = process.argv.slice(2)
  const bucketArg = args.find((a) => a.startsWith('--bucket='))
  const saPath = args.find((a) => !a.startsWith('--'))
    || process.env.GCP_SA_PATH
    || process.env.GOOGLE_APPLICATION_CREDENTIALS

  if (!saPath) {
    console.error(
      '[storage_inventory] No service account provided.\n' +
      '  Set GOOGLE_APPLICATION_CREDENTIALS (or GCP_SA_PATH) or pass the path as the first argument.\n' +
      '  This script is READ-ONLY: it only lists objects and writes the inventory markdown.'
    )
    process.exit(2)
  }

  let Storage
  try {
    ;({ Storage } = require('@google-cloud/storage'))
  } catch (e) {
    console.error('[storage_inventory] @google-cloud/storage is not installed. Run: npm i -D @google-cloud/storage')
    process.exit(2)
  }

  const storage = new Storage({ keyFilename: saPath })
  const bucketName = bucketArg
    ? bucketArg.split('=')[1]
    : process.env.VITE_FIREBASE_STORAGE_BUCKET || 'ironpulse.appspot.com'

  console.log(`[storage_inventory] Reading bucket "${bucketName}" (read-only)...`)
  const rows = []
  let totalBytes = 0
  try {
    const [files] = await storage.bucket(bucketName).getFiles()
    for (const file of files) {
      const [meta] = await file.getMetadata().catch(() => [{}])
      const size = Number(meta.size || 0)
      totalBytes += size
      rows.push({
        path: file.name,
        size,
        contentType: meta.contentType || '',
        updated: meta.updated || meta.timeCreated || '',
        md5: meta.md5Hash || '',
      })
    }
  } catch (e) {
    const code = e && (e.code || e.statusCode)
    const msg = String((e && e.message) || e)
    if (code === 404 || msg.includes('does not exist')) {
      console.log(`[storage_inventory] Source bucket "${bucketName}" does not exist (404). Recording EMPTY inventory.`)
    } else {
      throw e
    }
  }

  rows.sort((a, b) => a.path.localeCompare(b.path))

  // Summary by top-level folder
  const folders = {}
  for (const r of rows) {
    const top = r.path.split('/')[0] || '(root)'
    folders[top] = (folders[top] || 0) + 1
  }

  console.log(`\nObjects: ${rows.length}   Total bytes: ${totalBytes} (${(totalBytes / 1048576).toFixed(2)} MB)`)
  console.table(rows.map((r) => ({ path: r.path, bytes: r.size, type: r.contentType })))
  console.log('\nBy folder:')
  console.table(folders)

  // Missing/orphan heuristics: look for rows whose path does not start with a
  // known IRONPULSE prefix (members/, settings/) — candidates for orphan data.
  const knownPrefixes = ['members/', 'settings/']
  const orphans = rows.filter((r) => !knownPrefixes.some((p) => r.path.startsWith(p)))

  const doc = [
    '# FIREBASE STORAGE INVENTORY',
    '',
    `Generated by \`scripts/migration/storage_inventory.js\` (read-only) — bucket \`${bucketName}\`, ${new Date().toISOString()}`,
    '',
    '## Totals',
    '',
    `- Objects: **${rows.length}**`,
    `- Total size: **${(totalBytes / 1048576).toFixed(2)} MB** (${totalBytes} bytes)`,
    '',
    '## By folder',
    '',
    '| Folder | Count |',
    '|--------|-------|',
    ...Object.entries(folders).map(([k, v]) => `| ${k} | ${v} |`),
    '',
    '## Objects',
    '',
    '| Path | Bytes | Content-Type | Updated |',
    '|------|-------|--------------|---------|',
    ...rows.map((r) => `| \`${r.path}\` | ${r.size} | ${r.contentType} | ${r.updated} |`),
    '',
    '## Orphan / unrecognized paths',
    '',
    orphans.length
      ? orphans.map((r) => `- \`${r.path}\``).join('\n')
      : 'None — all objects live under known IRONPULSE prefixes (`members/`, `settings/`).',
    '',
    '## Source bucket status',
    '',
    rows.length
      ? `- Bucket \`${bucketName}\` is live with ${rows.length} objects (inventory above).`
      : `- Bucket \`${bucketName}\` returned **0 objects** (bucket absent/404 or empty). ` +
        'Independent evidence: `storage.buckets.list` on project `ironpulse-32f31` returns 0 buckets; ' +
        'Firestore scan (members `photoUrl`, settings `logoUrl`, all-collection URL fields) found 0 URL-shaped values. ' +
        'Step 8I treats the source as EMPTY — nothing to migrate.',
    '',
    '## Migration notes',
    '',
    '- This inventory is the baseline for Step 8F. No production files were moved by this script.',
    '- Path mapping: `members/{id}/profile.webp` → `members/{id}/profile.webp` (identical); `settings/gym-logo.webp` → `gyms/{gymId}/gym-logo.webp` (gym-scoped; logical id per gym must be re-uploaded since the legacy path carries no gym id).',
    '- Firebase download URLs stored in existing rows keep working while Firebase Storage stays enabled (rollback window).',
    '',
  ].join('\n')

  const outPath = path.join(__dirname, '..', '..', 'docs', 'FIREBASE_STORAGE_INVENTORY.md')
  fs.writeFileSync(outPath, doc, 'utf8')
  console.log(`\n[storage_inventory] Wrote ${outPath}`)
}

main().catch((err) => {
  console.error('[storage_inventory] Failed:', err.message || err)
  process.exit(1)
})
