// src/utils/planPdf.js
// ─────────────────────────────────────────────────────────────
// IRONPULSE — Printable plan export (Sprint 78B, req 8).
// Reuses jsPDF + jspdf-autotable (same deps as Reports.jsx).
// ─────────────────────────────────────────────────────────────

import { jsPDF } from 'jspdf'

const ACCENT = [232, 66, 10]

function header(doc, title, subtitle) {
  const w = doc.internal.pageSize.getWidth()
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(...ACCENT)
  doc.text(title, 14, 20)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(90, 90, 90)
  doc.text(subtitle, 14, 27)

  doc.setDrawColor(...ACCENT)
  doc.setLineWidth(0.8)
  doc.line(14, 31, w - 14, 31)
}

function footer(doc) {
  const w = doc.internal.pageSize.getWidth()
  const h = doc.internal.pageSize.getHeight()
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(`Generated by IRONPULSE · ${new Date().toLocaleDateString('en-IN')}`, 14, h - 10)
  doc.text(`Page ${doc.internal.getNumberOfPages()}`, w - 30, h - 10)
}

/** @param {Object} plan workout plan (workoutPlans document shape) */
export function exportWorkoutPlanPdf(plan) {
  if (!plan?.name) throw new Error('No workout plan to export')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  header(
    doc,
    plan.name,
    [
      plan.goal || '',
      plan.level || '',
      plan.days ? `${plan.days} day${plan.days > 1 ? 's' : ''}/week` : '',
      plan.duration || '',
      plan.split ? `Split: ${plan.split}` : '',
      plan.member ? `Assigned to: ${plan.member}` : '',
    ].filter(Boolean).join(' · ')
  )

  const body = (plan.exercises || []).map((ex, i) => [
    i + 1,
    ex.name || '',
    ex.muscle || '',
    String(ex.sets ?? ''),
    ex.reps || '',
    ex.rest || '',
    ex.notes || '',
  ])
  if (!body.length) body.push(['—', 'No exercises yet', '', '', '', '', ''])

  doc.autoTable({
    startY: 36,
    head: [['#', 'Exercise', 'Muscle', 'Sets', 'Reps', 'Rest', 'Notes']],
    body,
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: ACCENT, textColor: 255 },
    columnStyles: { 0: { cellWidth: 8 }, 5: { cellWidth: 16 } },
    margin: { left: 14, right: 14 },
  })

  footer(doc)
  doc.save(`${plan.name.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'workout-plan'}.pdf`)
}

/** @param {Object} plan diet plan (dietPlans document shape) */
export function exportDietPlanPdf(plan) {
  if (!plan?.name) throw new Error('No diet plan to export')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  header(
    doc,
    plan.name,
    [
      plan.goal || '',
      `Calories: ${plan.calories ? `${Number(plan.calories).toLocaleString()} kcal/day` : '—'}`,
      plan.protein ? `Protein ${plan.protein}g` : '',
      plan.carbs ? `Carbs ${plan.carbs}g` : '',
      plan.fat ? `Fat ${plan.fat}g` : '',
      plan.hydration ? `Hydration: ${plan.hydration}` : '',
      plan.duration ? `Duration: ${plan.duration}` : '',
      plan.assignedMember ? `Assigned to: ${plan.assignedMember}` : '',
    ].filter(Boolean).join(' · ')
  )

  const body = (plan.meals || []).map(m => [
    m.name || '',
    m.time || '',
    m.calories ? `${Number(m.calories).toLocaleString()} kcal` : '',
    Array.isArray(m.items) ? m.items.join('\n') : '',
  ])
  if (!body.length) body.push(['—', '', '', 'No meals yet'])

  doc.autoTable({
    startY: 40,
    head: [['Meal', 'Time', 'Calories', 'Items']],
    body,
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: ACCENT, textColor: 255 },
    columnStyles: { 3: { cellWidth: 90 } },
    margin: { left: 14, right: 14 },
  })

  footer(doc)
  doc.save(`${plan.name.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'diet-plan'}.pdf`)
}

export default {
  exportWorkoutPlanPdf,
  exportDietPlanPdf,
}
